[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "orga-analytics-geographic"
description = 'orga-analytics-geographic.'
readme = "README.md"
requires-python = ">=3.8"
keywords = ["python", "library", "logging", "handler", "databricks"]
authors = [
  { name = "Kehinde Adewusi", email = "kehinde.adewusi@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
]
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/kehindeadewusi/namespacy#readme"
Issues = "https://github.com/kehindeadewusi/namespacy/issues"
Source = "https://github.com/kehindeadewusi/namespacy"

[tool.setuptools.dynamic]
version = {attr = "orga.__about__.__version__"}

[tool.hatch.version]
path = "orga/__about__.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.envs.default]
dependencies = [
  "pytest==7.2.0",
  "pytest-cov==4.0.0",
  "pytest-mock==3.10.0",
  "requests-mock==1.10.0",
]

[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=orga --cov=tests"
no-cov = "cov --no-cov"

[[tool.hatch.envs.test.matrix]]
python = ["38", "39", "310", "311"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "orga/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.mypy]
warn_return_any = false
warn_unused_configs = true
ignore_missing_imports = true
exclude = [
    '^tests',
]
